/**
 * Seed the local dev database: migrations, pricing config, demo tenant,
 * and the mock wholesale catalog. Idempotent — safe to run repeatedly.
 *
 *   npm run db:seed
 */
import { ensurePgliteDir, getDb } from "../src/db";
import { appSettings, markupRules, tenants } from "../src/db/schema";
import { getWholesaleProvider } from "../src/lib/wholesale";
import { syncCatalog } from "../src/lib/catalog";

async function migrate() {
  // Migrations live in ./drizzle (generated by drizzle-kit).
  if (process.env.DATABASE_URL) {
    const { drizzle } = await import("drizzle-orm/postgres-js");
    const { migrate } = await import("drizzle-orm/postgres-js/migrator");
    const postgres = (await import("postgres")).default;
    const client = postgres(process.env.DATABASE_URL, { max: 1 });
    await migrate(drizzle(client), { migrationsFolder: "./drizzle" });
    await client.end();
  } else {
    const { PGlite } = await import("@electric-sql/pglite");
    const { drizzle } = await import("drizzle-orm/pglite");
    const { migrate } = await import("drizzle-orm/pglite/migrator");
    const client = new PGlite(ensurePgliteDir());
    await migrate(drizzle(client), { migrationsFolder: "./drizzle" });
    await client.close();
  }
}

async function main() {
  await migrate();
  console.log("✓ migrations applied");

  const db = await getDb();

  // Pricing config — placeholder values pending real wholesale quotes (Q1).
  const rules: Array<{ region: string; multiplier: string }> = [
    { region: "default", multiplier: "2.00" },
    { region: "europe", multiplier: "2.00" },
    { region: "usa", multiplier: "1.90" },
    { region: "asia", multiplier: "2.10" },
    { region: "middle_east", multiplier: "2.00" },
  ];
  for (const rule of rules) {
    await db
      .insert(markupRules)
      .values(rule)
      .onConflictDoUpdate({
        target: markupRules.region,
        set: { multiplier: rule.multiplier, updatedAt: new Date() },
      });
  }

  const settings: Array<{ key: string; value: string }> = [
    { key: "usd_ils_rate", value: "3.70" },
    { key: "fx_buffer", value: "0.03" },
    { key: "auto_refund_threshold_usd", value: "30" },
  ];
  for (const s of settings) {
    await db
      .insert(appSettings)
      .values(s)
      .onConflictDoNothing({ target: appSettings.key });
  }
  console.log("✓ pricing config seeded");

  // Demo agent tenants so multi-tenant skins (B2) have data to run against.
  const demoTenants = [
    {
      slug: "demo",
      displayName: "Demo eSIM",
      accentColor: "#F59E0B",
      commissionTier: "founding", // permanent 20% (D15)
      status: "active",
    },
    {
      slug: "yossi",
      displayName: "יוסי eSIM",
      accentColor: "#10B981",
      commissionTier: "standard",
      status: "active",
    },
  ];
  for (const t of demoTenants) {
    await db
      .insert(tenants)
      .values(t)
      .onConflictDoUpdate({
        target: tenants.slug,
        set: { commissionTier: t.commissionTier, status: t.status },
      });
  }
  console.log("✓ demo tenants seeded");

  const provider = getWholesaleProvider();
  const { upserted, deactivated } = await syncCatalog(db, provider);
  console.log(
    `✓ catalog synced from '${provider.id}': ${upserted} plans upserted, ${deactivated} deactivated`,
  );
}

main().then(
  () => process.exit(0),
  (err) => {
    console.error(err);
    process.exit(1);
  },
);
